# Site settings
title: eric li
email: eyli@princeton.edu
description: > # this means to ignore newlines until "baseurl:"
  personal website of eric li, designer + developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eli8527.github.io" # the base hostname & protocol for your site
twitter_username: eli8527
github_username:  eli8527

# Build settings
markdown: redcarpet

collections:
    projects:
        output: true
        permalink: /projects/:path/
    design:
        output: true
        permalink: /design/:path/
    